### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by qexxet** [Xepheryy/ICT1007#24]
I have tried to run your paper 3 code but it does not seem to work, it is infinitely looping at the light queue, have you resolved the issue?

**Comment by diddykong69** [comment]
Yes the issue has been resolved. Contact IT help-desk for more information.

**Comment by diddykong69** [comment]
> I have tried to run your paper 3 code but it does not seem to work, it is infinitely looping at the light queue, have you resolved the issue?

Can you share your input that caused the issue?

**Comment by qexxet** [comment]
I have used the test cases provided by the paper .
